### ISSUE TITLE
How to use the traefik_api_password part? 

### ISSUE THREAD

**Issue by thepenguinthatwants** [guillaumebriday/my-ansible-playbook#3]
Hi!

I was trying to use your traefik role.

But I got this warning

AnsibleFilterError: crypt.crypt does not support ''bcrypt'' algorithm'

Also

`msg: 'Failed to import the required Python library (Docker SDK for Python: docker (Python >= 2.7) or docker-py (Python 2.6)) The error was: No module named requests.exceptions'`

**Comment by guillaumebriday** [comment]
Hum

Try to add this tasks:

```yml
- name: Install pip
  easy_install:
    name: pip
    state: latest

- name: Add the Python client for Docker
  pip:
    name: docker-py
```

Does it work ?

I will add it in the repo if needed
